[runtime]
auto_reload = "autorun"
on_cell_change = "autorun"
auto_instantiate = true

[server]
browser = "default"
follow_symlink = false

[ai]
rules = ""
[ai.google]

[ai.open_ai]
api_key = "${MARIMO_OPENAI_API_KEY}"
base_url = "https://api.openai.com/v1"
model = "claude-"

[ai.anthropic]
api_key = "${MARIMO_ANTHROPIC_API_KEY}"

[completion]
activate_on_typing = true
copilot = "github"

[package_management]
manager = "uv"

[formatting]
line_length = 120

[save]
format_on_save = true
autosave_delay = 1000
autosave = "after_delay"

[display]
default_width = "full"
cell_output = "above"
dataframes = "rich"
code_editor_font_size = 16
theme = "dark"

[keymap]
preset = "vim"

[keymap.overrides]

[experimental]
